

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebTarefa
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TarefaDBEntities : DbContext
{
    public TarefaDBEntities()
        : base("name=TarefaDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<TB_TAREFA> TB_TAREFA { get; set; }

}

}

