
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebTarefa
{

using System;
    using System.Collections.Generic;
    
public partial class TB_TAREFA
{

    public int Id { get; set; }

    public string Descricao { get; set; }

    public System.DateTime DtAtividade { get; set; }

    public System.DateTime DtEntrega { get; set; }

    public System.DateTime DtLimEntrega { get; set; }

}

}
